{{/*
clusterRole resources with range loop
*/}}

{{- if .Values.clusterRoles }}
{{- range $name, $roleObject := .Values.clusterRoles }}
{{- if $roleObject.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $name }}
  labels:
    {{- include "rbac.labels" $ | nindent 4 }}
    {{- with $roleObject.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  {{- range $rule := $roleObject.rules }}
  - apiGroups: 
      {{- toYaml $rule.apiGroups | nindent 6 }}
    resources:
      {{- toYaml $rule.resources | nindent 6 }}
    verbs:
      {{- toYaml $rule.verbs | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}