{{/*
clusterRoleBinding resources with range loop
*/}}

{{- if .Values.clusterRoleBindings }}
{{- range $name, $binding := .Values.clusterRoleBindings }}
{{- if $binding.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $name }}
  labels:
    {{- include "rbac.labels" $ | nindent 4 }}
    {{- with $binding.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: {{ $binding.roleRef.apiGroup | default "rbac.authorization.k8s.io" }}
  kind: {{ $binding.roleRef.kind }}
  name: {{ $binding.roleRef.name }}
subjects:
  - apiGroup: {{ $binding.subjects.apiGroup | default "rbac.authorization.k8s.io" }}
    kind: {{ $binding.subjects.kind }}
    name: {{ $binding.subjects.name }}
{{- end }}
{{- end }}
{{- end }}