{{/*
role resources with range loop
*/}}

{{- range $namespace, $roles := .Values.roles }}
{{- range $name, $role := $roles }}
{{- if $role.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- include "rbac.labels" $ | nindent 4 }}
    {{- with $role.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
  {{- range $rule := $role.rules }}
  - apiGroups:
      {{- toYaml $rule.apiGroups | nindent 6 }}
    resources:
      {{- toYaml $rule.resources | nindent 6 }}
    {{- if $rule.resourceNames }}
    resourceNames:
      {{- toYaml $rule.resourceNames | nindent 6 }}
    {{- end }}
    verbs:
      {{- toYaml $rule.verbs | nindent 6 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}