jobs:
  test:
    steps:
      # Ref: https://stackoverflow.com/questions/71180135/github-actions-how-can-i-cache-the-docker-images-for-testcontainers
      - name: Create cache directory
        run: mkdir -p /tmp/docker-cache

      - name: Cache ECR testcontainers images
        id: image-cache
        uses: actions/cache@v4
        with:
          path: /tmp/docker-cache
          key: ecr-testcontainers-images-${{ runner.os }}-v1
          restore-keys: |
            ecr-testcontainers-images-${{ runner.os }}-

      - name: Pull and save ECR images
        if: steps.image-cache.outputs.cache-hit != 'true'
        env:
          ECR_REGISTRY: my.ecr.com
        run: |
          docker pull ${{ env.ECR_REGISTRY }}/mysql:8.0.39
          docker save -o /tmp/docker-cache/mysql.tar ${{ env.ECR_REGISTRY }}/mysql:8.0.39
          docker pull ${{ env.ECR_REGISTRY }}/valkey:8.1.0-alpine
          docker save -o /tmp/docker-cache/valkey.tar ${{ env.ECR_REGISTRY }}/valkey:8.1.0-alpine

      - name: Load cached Docker images
        if: steps.image-cache.outputs.cache-hit == 'true'
        run: |
          docker load -i /tmp/docker-cache/mysql.tar
          docker load -i /tmp/docker-cache/valkey.tar