{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "squid.fullname" . }}-cache
  labels:
    {{- include "squid.labels" . | nindent 4 }}
  {{- with include "squid.mergedAnnotations" (dict "common" .Values.commonAnnotations "resource" .Values.persistence.annotations) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  {{- if eq "-" .Values.persistence.storageClassName }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  {{- end }}
  {{- if .Values.persistence.volumeName }}
  volumeName: {{ .Values.persistence.volumeName }}
  {{- end }}
{{- end }}