{{- if and .Values.squidExporter.enabled .Values.squidExporter.squidPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "squid.fullname" . }}-exporter-auth
  labels:
    {{- include "squid.labels" . | nindent 4 }}
  {{- with include "squid.mergedAnnotations" (dict "common" .Values.commonAnnotations "resource" nil) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.squidExporter.squidPassword | b64enc | quote }}
{{- end }}