# -- Deploy Argo CD Applications within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
global:
  environment: dev

applications:
- name: keda
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: keda
  destination:
    namespace: keda
  syncPolicy:
    automated: {}

- name: secrets-store-csi-driver
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kube-system/secrets-store-csi-driver
  destination:
    namespace: kube-system
  syncPolicy:
    automated: {}

- name: aws-load-balancer-controller
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kube-system/aws-load-balancer-controller
  destination:
    namespace: kube-system
  syncPolicy:
    automated: {}

- name: aws-node-termination-handler
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kube-system/aws-node-termination-handler
  destination:
    namespace: kube-system
  syncPolicy:
    automated: {}

- name: cluster-autoscaler
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kube-system/cluster-autoscaler
  destination:
    namespace: kube-system
  syncPolicy:
    automated: {}

- name: kyverno
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kyverno
  destination:
    namespace: kyverno
  syncPolicy:
    automated: {}

- name: kyverno-policies
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kyverno-policies
  destination:
    namespace: kyverno
  syncPolicy:
    automated: {}

- name: kube-state-metrics
  additionalLabels: {}
  additionalAnnotations: {}
  project: infra
  source:
    path: kube-system/kube-state-metrics
  destination:
    namespace: kube-system
  syncPolicy:
    automated: {}

# -- Deploy Argo CD Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
projects:
- name: backend
  additionalLabels: {}
  additionalAnnotations: {}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  description: "backend project (Managed by Helm chart)"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist: []
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist: []
  orphanedResources: {}
  roles: []
  syncWindows: []
  signatureKeys: []

- name: frontend
  additionalLabels: {}
  additionalAnnotations: {}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  description: "frontend project (Managed by Helm chart)"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist: []
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist: []
  orphanedResources: {}
  roles: []
  syncWindows: []
  signatureKeys: []

- name: data
  additionalLabels: {}
  additionalAnnotations: {}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  description: "data project (Managed by Helm chart)"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceBlacklist: []
  namespaceResourceBlacklist: []
  namespaceResourceWhitelist: []
  orphanedResources: {}
  roles: []
  syncWindows: []
  signatureKeys: []

# -- Deploy Argo CD ApplicationSets within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
applicationsets: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   # See PR #10026 (ArgoCD v2.5 or later)
#   # goTemplate: false
#   generators:
#   - git:
#       repoURL: https://github.com/argoproj/argocd-example-apps.git
#       revision: HEAD
#       directories:
#       - path: guestbook
#       - path: kustomize-*
#   # Ref https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Controlling-Resource-Modification/#allow-temporarily-toggling-auto-sync
#   ignoreApplicationDifferences:
#   - jsonPointers:
#     - /spec/syncPolicy
#   # Progressive Syncs is an experimental feature and it must be explicitly enabled
#   # Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Progressive-Syncs/#enabling-progressive-syncs
#   strategy:
#     type: RollingSync
#     rollingSync:
#       steps:
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - guestbook
#       - matchExpressions:
#         - key: project
#           operator: In
#           values:
#           - kustomize-foo
#           - kustomize-bar
#   template:
#     metadata:
#       name: '{{path.basename}}'
#       labels:
#         project: '{{path.basename}}'
#       annotations: {}
#     spec:
#       project: default
#       source:
#         repoURL: https://github.com/argoproj/argocd-example-apps.git
#         targetRevision: HEAD
#         path: '{{path}}'
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: default
#       syncPolicy:
#         automated:
#           prune: false
#           selfHeal: false
#       ignoreDifferences:
#       - group: apps
#         kind: Deployment
#         jsonPointers:
#         - /spec/replicas
#       info:
#       - name: url
#         value: https://argoproj.github.io/
#   syncPolicy:
#     # Set Application finalizer
#     preserveResourcesOnDeletion: false

# --  Deploy Argo CD Applications/ApplicationSets/Projects within this helm release
# @default -- `[]` (See [values.yaml])
## Ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/
itemTemplates: []
# - items:
#     - name: my-appset
#       generators: &generators
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template:
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: "{{ .name }}"
#     spec:
#       generators: *generators
#       template:
#         metadata:
#           name: "{{`{{cluster}}`}}-guestbook"
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: "{{`{{cluster}}`}}"
#             namespace: guestbook
# - items:
#     - name: my-appset
#       generators:
#         - list:
#             elements:
#               - cluster: engineering-dev
#                 url: https://1.2.3.4
#               - cluster: engineering-prod
#                 url: https://2.4.6.8
#               - cluster: finance-preprod
#                 url: https://9.8.7.6
#   template: |-
#     apiVersion: argoproj.io/v1alpha1
#     kind: ApplicationSet
#     metadata:
#       name: {{ .name }}
#     spec:
#       generators: {{ toYaml .generators | nindent 4 }}
#       template:
#         metadata:
#           name: '{{`{{cluster}}`}}-guestbook'
#         spec:
#           project: my-project
#           source:
#             repoURL: https://github.com/infra-team/cluster-deployments.git
#             targetRevision: HEAD
#             path: guestbook/{{`{{cluster}}`}}
#           destination:
#             server: '{{`{{cluster}}`}}'
#             namespace: guestbook

# -- DEPRECATED - Please refer [Deprecation Notice](https://github.com/argoproj-labs/argocd-extensions?tab=readme-ov-file#deprecation-notice) for more info.
# @default -- `[]` (See [values.yaml])
## This function in tech preview stage, do expect unstability or breaking changes in newer versions. Bump image.tag if necessary.
## Ref: https://github.com/argoproj-labs/argocd-extensions
extensions: []
  # - name: example
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations: {}
  #   sources:
  #     - git:
  #         url: https://github.com/argoproj-labs/argocd-example-extension.git
  #     - web:
  #         url: https://github.com/argoproj-labs/argocd-example-extension/releases/download/v0.1.0/extension.tar
