{{/*
Overprovisioning deployment template for maintaining spare capacity
*/}}

{{- range $nodePoolName, $nodePoolConfig := .Values.nodePool }}
{{- if and $nodePoolConfig.overprovisioning $nodePoolConfig.overprovisioning.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overprovisioning-dummy-{{ $nodePoolName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels" $ | nindent 4 }}
    app.kubernetes.io/component: overprovisioning
    karpenter.sh/nodepool: {{ $nodePoolName }}
  {{- if $.Values.globalAnnotations }}
  annotations:
    {{- include "annotations" $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ $nodePoolConfig.overprovisioning.nodes | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: overprovisioning
      karpenter.sh/nodepool: {{ $nodePoolName }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: overprovisioning
        karpenter.sh/nodepool: {{ $nodePoolName }}
        {{- include "labels" $ | nindent 8 }}
        {{- with $nodePoolConfig.overprovisioning.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if $nodePoolConfig.overprovisioning.podAnnotations }}
      annotations:
        {{- with $nodePoolConfig.overprovisioning.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      containers:
      - name: overprovisioning-dummy
        image: registry.k8s.io/pause:3.9
        {{- with $nodePoolConfig.overprovisioning.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      priorityClassName: overprovisioning-low-priority
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/nodepool
                operator: In
                values: [{{ $nodePoolName }}]
      {{- with $nodePoolConfig.overprovisioning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $nodePoolConfig.overprovisioning.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
